version: '3.8'

services:
  user-service:
    image: user-service
    ports:
      - "5002:5002"
    env_file:
      - userenv.list
    restart: always
    depends_on:
      - user-db
      - rabbitmq
    networks:
      - user
      - rabbitmq
  user-db:
    container_name: user-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'cmux-password'
      MYSQL_DATABASE: 'sda-user'
    ports:
      - 3307:3306
    networks:
      - user
    

  # gateway-service:
  #   image: gateway-service
  #   ports:
  #     - "5001:5001"
  #   env_file:
  #     - gatewayenv.list
  #   depends_on:
  #     - user-service
  #   networks:
  #     - user
  # chat-service:
  #   image: chat-service
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - cassandra
  #     - rabbitmq
  #     - cassandra-load-keyspace
  #   environment:
  #     CASSANDRA_HOST: cassandra
  #     RABBITMQ_HOST: rabbitmq
  #     AWS_ACCESS_KEY_ID: AKIA2USN5UESAF6CJXE5
  #     AWS_SECRET_ACCESS_KEY: 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
  #     AWS_REGION: us-east-2
      
  # cassandra:
  #   image: "cassandra:latest"
  #   ports:
  #     - "9042:9042"
  #   restart: always
  #   volumes:
  #     - cassandra-data:/var/lib/cassandra

  # cassandra-load-keyspace:
  #     container_name: cassandra-load-keyspace
  #     image: cassandra:latest
  #     depends_on:
  #       - cassandra
  #     volumes:
  #       - ./chat/src/main/resources/cassandra_schema.cql:/schema.cql 
  #     command: /bin/bash -c "sleep 180 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  reward-service:
    image: reward-service
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - reward-db
      - rabbitmq
      - user-service
    networks:
      - reward
      - user
      - rabbitmq

  reward-db:
    container_name: user-credit
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'sda-reward'
      MYSQL_USER: 'reward'
      MYSQL_PASSWORD: 'password'
    ports:
      - 3308:3306
    networks:
      - reward

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    networks:
      - rabbitmq

networks:
  reward: 
    driver: bridge
  rabbitmq:
    driver: bridge
  user:
    driver: bridge

volumes:
  cassandra-data: