apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  CASSANDRA_HOST: cassandra
  RABBITMQ_HOST: rabbitmq
  AWS_ACCESS_KEY_ID: AKIA2USN5UESAF6CJXE5
  AWS_SECRET_ACCESS_KEY: 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
  AWS_REGION: us-east-2
  SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
  SPRING_CASSANDRA_KEYSPACE_NAME: cmux_chat
  SPRING_CASSANDRA_CONTACT_POINTS: "cassandra:9042"
  SPRING_CASSANDRA_SCHEMA_ACTION: CREATE_IF_NOT_EXISTS
  SPRING_CASSANDRA_REQUEST_TIMEOUT: 10s
  SPRING_CASSANDRA_CONNECTION_CONNECT_TIMEOUT: 10s
  SPRING_CASSANDRA_CONNECTION_INIT_QUERY_TIMEOUT: 10s
