apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat-container
          image: liyangc2/chat-service
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: chat-config
