apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-config
data:
  NEO4J_URI: bolt://neo4j-service:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: cmuxpassword
  SPRING_NEO4J_URI: bolt://neo4j-service:7687
  SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: bitnami1
  SPRING_DATA_NEO4J_DATABASE: neo4j
  SERVER_PORT: "8080"
  RABBITMQ_QUEUE_NAME_NEWUSER: "cmu-x-subscription-newuser"
  RABBITMQ_EXCHANGE_NAME: "cmuxExchange"
  RABBITMQ_EXCHANGE_FANOUT_NAME: "cmuxfanoutExchange"
  RABBITMQ_REWARD_ROUTING_KEY: "cmux-newfollower"


