apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-redis
  template:
    metadata:
      labels:
        app: user-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
