apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-env
data:
  JWT_SECRET_KEY: myVerySecretAndComplexKey!@#2023
  JWT_EXPIRATION_MS: "3600000"
  JWT_REFRESH_EXPIRATION_MS: "604800000"
  SERVER_PORT: "5001"
  SPRING_MAIN_WEB_APPLICATION_TYPE: reactive
