version: '3.8'

services:
  subscription-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: subscription-service:latest
    ports:
      - "8082:8082" 
    environment:
      SPRING_NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: cmuxpassword
    depends_on:
      - neo4j
    networks:
      - subscribe
    

  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/cmuxpassword
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - subscribe

networks:
  subscribe:

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
